export default {
    appKey: "vtexappkey-denon-QGPOPF",
    appToken: "AUHQUBHOROMOTDMPTLUDIGZITVRCMTJCIUVLHJZBTSUXECLPFPYQYXJTUZWYJECXEJFZHBHKLSJPMBERJCXWVSELLCQINBRPQWTVWMHEINFFNTGTVEPHHGCMFUNFKYXK",
};